__title__ = "cartpole"
__description__ = "A CartPole implementation in Python using reinforcement learning."
__url__ = "https://github.com/ThomasByr/RL-CartPole"
__version__ = "1.1.2"
__author__ = "Thomas Byr"
__author_email__ = "tbouyer2000@gmail.com"
__license__ = "GNU GPLv3"
__copyright__ = "Copyright (c) 2021 Thomas Byr"
